[package]
name = "miro-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1", features = ["shell"] }

[build-dependencies]
tauri-build = { version = "1", features = [] }
